name: MRE-SIPAN
channels:
 - defaults
dependencies:
  - python=3.9.12
  - scikit-learn=1.0.2
  - numpy=1.21.5
  - pandas=1.4.2
  - sqlalchemy=1.4.39
  - pyodbc
  - pip:
    - xgboost==1.6.1

